name: teching
favicon: null
layout_spectrum: 0.2928476280067116
typography_spectrum: 0.54435
title: Teching The Tech
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0084ff'
    - '#000000'
    - '#9fd1ff'
    - '#848484'
  brandStrength: 0.08735290472395718
  lightness: 0.8165362481959164
  saturation: 0.029634211445227265
  rhythmicContrast: 0.4998498859349638
purpose: []
